Added description from ingredient list in specific recipe to shopping list equivalent
TandoorRecipes/recipes pull request #2213
Opened 2022-12-13 04:02 UTC by MonkeyJerr

Resolves #2178 
| Before: | After |
| --------| -------------|
| ![TandoorScreenshot](https://user-images.githubusercontent.com/79874674/207223431-6e610bb5-9401-4df9-8f3c-7eac940c2edf.png) | ![ConfirmedChanges](https://user-images.githubusercontent.com/79874674/207223456-257998cc-20d2-4115-9617-bfce4a62cc91.png) |

2022-12-13 04:10 UTC, MonkeyJerr commented
@vabene1111 wondering if we could get a review on this

2023-01-10 08:28 UTC, lewisushindi approved these changes

2023-10-05 11:47 UTC, akashin commented
@MonkeyJerr,  Heya! I've been looking for a similar feature and was wondering whether you plan to submit this? If not, I can try to rebase this change and propose a PR myself. Thanks :)

2023-10-05 16:12 UTC, vabene1111 requested changes

2023-10-05 16:14 UTC, vabene1111 commented
I am so sorry, I always forget to submit the review after writing the comments. In general I liked the feature so I would merge it, it needs rebasing as it was left open for so long.

2024-01-23 15:21 UTC, closed without merging