Improve parsing of OpenEats imports
TandoorRecipes/recipes pull request #2379
Opened 2023-03-20 18:20 UTC by thomaspreece

Updated the code to be able to parse tags, cuisine and course out of OpenEats. Also parses comments and ratings and allows for transfer of images from OpenEats.

Documentation updated to include process of how to import the extra data

2023-03-21 07:45 UTC, vabene1111 commented
Very cool, thank you.

I added a few notes I found while looking at the code, maybe you could take look before I get it merged.

2023-03-24 06:48 UTC, vabene1111 commented
that is very strange. If you open the files changed tab you dont see any comments anywhere and also not in the timeline on this page? From what I found in GH's docs this should be publicly visible and I also can't find any setting to toggle visibility.

2023-03-25 05:02 UTC, vabene1111 requested changes

2023-03-25 05:02 UTC, vabene1111 commented
ok so i googled again, i needed to submit the review with a change request so that you can see my comments. You learn someting new everyday 😂  now you should be able to see what i wrote

2023-03-28 16:29 UTC, thomaspreece commented on docs/features/import_export.md
> +To import your images you'll need to create the folder `openeats-import` in your Tandoor's `recipes` media folder (which is usually found inside `/opt/recipes/mediafiles`). After that you'll need to
I think the zip file approach is probably better (as that will allow for processing the images to be web friendly, etc). However, for the time being I think this option is a good stopgap.

2023-03-28 16:33 UTC, thomaspreece commented on cookbook/integration/openeats.py
> +            instructions += f'\nRecipe source: [{file["source"]}]({file["source"]})'
I've added `from django.utils.translation import gettext as _` and wrapped my text now but I'm having trouble getting the po files to update. Running `django-admin makemessages -a -s` doesn't seem to update the locale files. I've not used Django before so any tips would be welcome.

2023-03-28 19:00 UTC, vabene1111 commented on cookbook/integration/openeats.py
> +            instructions += f'\nRecipe source: [{file["source"]}]({file["source"]})'
Just wrap it, I can recreate the files the nwxt time I update translations

2023-03-29 14:04 UTC, merged