Reorder books #2338
TandoorRecipes/recipes pull request #2810
Opened 2023-12-15 01:48 UTC by m7modSy

Implemented the ability to sort books in four different ways:

1. **Oldest to Newest:** Sorts books based on their creation date.
2. **Newest to Oldest:** Sorts books in reverse order of creation date.
3. **Alphabetical Order:** Sorts books alphabetically.
4. **Manual Sorting:** Users can now manually reorder books. Changes are saved persistently, even after leaving the website.

Manual Sorting Features:

- Swap: Users can swap the positions of two directly adjacent books.
- Specify Location: Users can specify the desired location for a book.
- Drag-and-Drop: Initially considered, but not implemented to ensure efficiency, especially for users on mobile devices.

**Note:** This pull request addresses [issue #2338](https://github.com/TandoorRecipes/recipes/issues/2338).

2023-12-15 13:12 UTC, smilerz commented
- ordering should be handled within the API instead of on the front end
- manually ordering should be added to the Book model and be persistent

2023-12-16 06:44 UTC, vabene1111 commented
Hi, thanks for your PR. As smilerz said there is some room for improvement, espcecially since this adds a lot of code to the frontend. 

We usually do ordering in tandoor by adding an `order` field to the model (see for example MealType). 

For automatic ordering this is not needed as you could just add a query param to the API, for manual ordering that field could be edited by the user (not very user friendly but thats also the case for properties) but automatic ordering and manual ordering could conflict so that needs to be taken into account.

2023-12-16 06:46 UTC, vabene1111 requested changes
see comments above, please also make sur to share a draft of what you want to do before writing code so that we can save you time by giving feedback directly (see https://docs.tandoor.dev/contribute/)

2023-12-17 15:36 UTC, m7modSy commented
Hallo, 
Thank you guys @smilerz @vabene1111  for your Feedback on my PR :)

For automatic ordering i think its pretty straight forward.  i added 2 options for ordering through the api client
1. order_field: Specify the field to order by
2. Specify 'asc' for ascending order or 'desc' for descending order.

manual ordering:
I am very confused here:
I have seen how you handle the field order. My thoughts are that I make an update request with every swap, but is that really efficient or even possible?

2023-12-18 15:58 UTC, smilerz commented
> manual ordering: I am very confused here: I have seen how you handle the field order. My thoughts are that I make an update request with every swap, but is that really efficient or even possible?

ascending and descending should be part of the API/Serializer, not the model.
The behavior on the API is handled through a combination of Model, API and Serializer.  (model.py, api.py and serializer.py)

Take a look at SupermarketCategory for an example on how this has been handled.

2024-01-08 15:38 UTC, m7modSy commented
Hi @smilerz and @vabene1111,
you can take a look now at the code :)
you can now change the manual order by dragging and dropping, exactly like the SupermarketCategory

2024-01-28 07:48 UTC, vabene1111 reviewed
ok finally got around to reviewing this, just 2 minor changes and we are good to go

2024-01-28 07:48 UTC, vabene1111 commented on cookbook/views/api.py
> +import json
please have imports on the top of the file

2024-01-28 07:48 UTC, vabene1111 commented on cookbook/migrations/0206_recipebook_order.py
can you delete the migration from the PR please, I will create it after merging so that the line is correct.

2024-02-16 18:53 UTC, merged